Merge branch 'develop' into feat/add-image-clickurl

diff --git a/.github/workflows/pr-preview.yml b/.github/workflows/pr-preview.yml
--- a/.github/workflows/pr-preview.yml
+++ b/.github/workflows/pr-preview.yml
@@ -23,7 +23,7 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           fetch-depth: 1
 
@@ -114,7 +114,7 @@ jobs:
 
     steps:
       - name: Checkout Streamlit code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           persist-credentials: false
           submodules: "recursive"
@@ -131,8 +131,14 @@ jobs:
         timeout-minutes: 120
         run: |
           sudo apt update
-          sudo apt install rsync
+          sudo apt install rsync jq
           make package
+          INDEX_NAME=$(jq '."index.html".name' lib/streamlit/static/manifest.json | tr -d '"')
+          if [[ "${INDEX_NAME}" != "index" ]]
+          then
+            echo 'lib/streamlit/static/manifest.json is missing or malformatted!'
+            exit 1
+          fi
       - name: Store Whl File
         uses: actions/upload-artifact@v4
         with:
@@ -385,7 +391,7 @@ jobs:
 
     steps:
       - name: Checkout Core Previews Repo
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           repository: streamlit/core-previews
           # The default GITHUB_TOKEN is scoped only to the triggering streamlit/streamlit repo.
@@ -429,7 +435,7 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           fetch-depth: 1
 
