Clean up

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,12 +1,12 @@
 name: Build Release
 
-on:
-  # TODO: Add Manual Trigger
+on: 
+  workflow_dispatch:
 
   # FOR TESTING ONLY:
-  push:
-    branches:
-      - '**'
+  # push:
+  #   branches:
+  #     - '**'
 
 jobs:
   build-release:
@@ -39,33 +39,33 @@ jobs:
       - name: Configure GitHub CLI Settings
         env:
           REPO: ${{ github.repository }}
-        run: echo "GH_REPO="$REPO"" >> $GITHUB_ENV
+        run: echo 'GH_REPO="$REPO"' >> $GITHUB_ENV
       - name: Look up the related GitHub PR number and branch name
         env:
           GH_REPO: ${{ env.GH_REPO }}
         run: |
           eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-          echo "GH_PR_BRANCH=$(gh api repos/${GH_REPO}/pulls | jq '[.[] | select(.head.label | contains("release/"))] | .[0] | .head.ref')" >> $GITHUB_ENV
-      # - name: Ensure that version tag matches branch version
-      #   run: |
-      #     if [ "$(echo $GH_PR_BRANCH | tr -d 'release/')" != "$GIT_TAG" ]
-      #     then
-      #       echo "ERROR: Version number from tag does not match the version number from the branch name."
-      #       exit 1
-      #     fi
+          echo 'GH_PR_BRANCH=$(gh api repos/"$GH_REPO"/pulls | jq '[.[] | select(.head.label | contains("release/"))] | .[0] | .head.ref')' >> $GITHUB_ENV
+      - name: Ensure that version tag matches branch version
+        run: |
+          if [ '$(echo "$GH_PR_BRANCH" | tr -d 'release/')' != "$GIT_TAG" ]
+          then
+            echo "ERROR: Version number from tag does not match the version number from the branch name."
+            exit 1
+          fi
       - name: Checkout head of branch
         env:
           GH_PR_BRANCH: ${{ env.GH_PR_BRANCH }}
         run: |
-          git pull origin ${GH_PR_BRANCH} --ff-only
+          git pull origin "$GH_PR_BRANCH" --ff-only
       - name: Setup virtual env
         uses: ./.github/actions/make_init
       - name: Set release version from tag name
-        run: echo "STREAMLIT_RELEASE_VERSION=$(echo "$GIT_TAG")" >> GITHUB_ENV
+        run: echo 'STREAMLIT_RELEASE_VERSION=$(echo "$GIT_TAG")' >> GITHUB_ENV
       - name: Update version
         env:
           STREAMLIT_RELEASE_VERSION: ${{ env.STREAMLIT_RELEASE_VERSION }}
-        run: python scripts/update_version.py $STREAMLIT_RELEASE_VERSION
+        run: python scripts/update_version.py "$STREAMLIT_RELEASE_VERSION"
       - name: Create Package
         timeout-minutes: 120
         run: |
@@ -75,27 +75,21 @@ jobs:
         run: make cli-regression-tests
       - name: Store Package
         uses: actions/upload-artifact@v3
-        if: always()
         with:
           path: lib/dist
-
-      # TODO: Need the streamlit PyPI user/password for the below steps - added the if statement to gate for now
-      - if: ${{ 'true' == 'false' }}
-        name: Initialize .pypirc
+      - name: Initialize .pypirc
         env:
           STREAMLIT_PYPI_USERNAME: ${{ secrets.STREAMLIT_PYPI_USERNAME }}
           STREAMLIT_PYPI_API_TOKEN: ${{ secrets.STREAMLIT_PYPI_API_TOKEN }}
         run: |
-            cd lib
-            echo -e "[pypi]" >> ~/.pypirc
-            echo -e "username = "$STREAMLIT_PYPI_USERNAME"" >> ~/.pypirc
-            echo -e "password = "$STREAMLIT_PYPI_API_TOKEN"" >> ~/.pypirc
-      - if: ${{ 'true' == 'false' }}
-        name: Upload to PyPI
+          cd lib
+          echo -e "[pypi]" >> ~/.pypirc
+          echo -e 'username = "$STREAMLIT_PYPI_USERNAME"' >> ~/.pypirc
+          echo -e 'password = "$STREAMLIT_PYPI_API_TOKEN"' >> ~/.pypirc
+      - name: Upload to PyPI
         run: |
           make distribute
-      - if: ${{ 'true' == 'false' }}
-        name: Commit version updates
+      - name: Commit version updates
         env:
           GH_PR_BRANCH: ${{ env.GH_PR_BRANCH }}
           STREAMLIT_RELEASE_VERSION: ${{ env.STREAMLIT_RELEASE_VERSION }}
@@ -105,11 +99,23 @@ jobs:
 
           git switch -c "$GH_PR_BRANCH"
 
-          git commit -am "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]" && git push origin "$GH_PR_BRANCH" || echo "No changes to commit"
-      - if: ${{ 'true' == 'false' }}
-        name: Create GitHub Release
+          git commit -am 'Up version to "$STREAMLIT_RELEASE_VERSION"' && git push origin "$GH_PR_BRANCH" || echo "No changes to commit"
+      - name: Create GitHub Release
         env:
           GIT_TAG: ${{ env.GIT_TAG }}
         run: |
           eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
           gh release create "$GIT_TAG" -n "" -t "$GIT_TAG"
+      # TODO: Using testing webhook, switch to actual st-open-source channel webhook later
+      - name: Successful Release Slack Message
+        if: ${{ success() }}
+        env: 
+          SLACK_WEBHOOK: ${{ secrets.TEST_SLACK_WEBHOOK }}
+        run: |
+          curl -X POST -H 'Content-type: application/json' --data '{"text":":rocket: Release was successful!"}' "$SLACK_WEBHOOK"
+      - name: Failed Release Slack Message
+        if: ${{ failure() }}
+        env: 
+          SLACK_WEBHOOK: ${{ secrets.TEST_SLACK_WEBHOOK }}
+        run: |
+          curl -X POST -H 'Content-type: application/json' --data '{"text":":blobonfire: Release failed"}' "$SLACK_WEBHOOK"
