Add back branch check to verify that corresponding PR exists

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -83,6 +83,23 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "${{ env.PYTHON_MAX_VERSION }}"
+      - name: Look up the related GitHub PR branch name
+        # Need GH Token to use gh api
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          pip install requests
+          echo "GH_PR_BRANCH=$(python scripts/get_release_branch.py)" >> $GITHUB_ENV
+      - name: Ensure release branch corresponding to this tag exists
+        env:
+          GH_PR_BRANCH: ${{ env.GH_PR_BRANCH }}
+        run: |
+          BRANCH_VERSION=$(echo "$GH_PR_BRANCH" | sed 's/release\///' )
+          if [ "$BRANCH_VERSION" != "$GIT_TAG" ]
+          then
+            echo "ERROR: release branch corresponding to this tag does not exist."
+            exit 1
+          fi
       - name: Setup virtual env
         uses: ./.github/actions/make_init
       - name: Set release version from tag name
